name: AestheticalXD
main: xyz.aesthetical.manhunt.Main
version: 1.0

commands:
  hunter:
    description: Configures hunters
    usage: /<command> [list | target | add | remove] [playerName]
    permission: none
    permission-message: You don't have <permission>